<?php
/**
 * SaveTicketSettingsRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * wallet-api
 *
 * API
 *
 * The version of the OpenAPI document: 2.1.600
 * Contact: development@wallet.inc
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * SaveTicketSettingsRequest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SaveTicketSettingsRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'saveTicketSettings_request';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'redemption_instructions' => 'string',
        'ticket_expiration_date_time' => '\DateTime',
        'max_comp_tickets' => 'float',
        'payment_design_id' => '\OpenAPI\Client\Model\SaveTicketSettingsRequestPaymentDesignID'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'redemption_instructions' => null,
        'ticket_expiration_date_time' => 'date-time',
        'max_comp_tickets' => 'double',
        'payment_design_id' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'redemption_instructions' => false,
        'ticket_expiration_date_time' => false,
        'max_comp_tickets' => false,
        'payment_design_id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'redemption_instructions' => 'redemptionInstructions',
        'ticket_expiration_date_time' => 'ticketExpirationDateTime',
        'max_comp_tickets' => 'maxCompTickets',
        'payment_design_id' => 'paymentDesignID'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'redemption_instructions' => 'setRedemptionInstructions',
        'ticket_expiration_date_time' => 'setTicketExpirationDateTime',
        'max_comp_tickets' => 'setMaxCompTickets',
        'payment_design_id' => 'setPaymentDesignId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'redemption_instructions' => 'getRedemptionInstructions',
        'ticket_expiration_date_time' => 'getTicketExpirationDateTime',
        'max_comp_tickets' => 'getMaxCompTickets',
        'payment_design_id' => 'getPaymentDesignId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('redemption_instructions', $data ?? [], null);
        $this->setIfExists('ticket_expiration_date_time', $data ?? [], null);
        $this->setIfExists('max_comp_tickets', $data ?? [], null);
        $this->setIfExists('payment_design_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['ticket_expiration_date_time'] === null) {
            $invalidProperties[] = "'ticket_expiration_date_time' can't be null";
        }
        if ($this->container['max_comp_tickets'] === null) {
            $invalidProperties[] = "'max_comp_tickets' can't be null";
        }
        if ($this->container['payment_design_id'] === null) {
            $invalidProperties[] = "'payment_design_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets redemption_instructions
     *
     * @return string|null
     */
    public function getRedemptionInstructions()
    {
        return $this->container['redemption_instructions'];
    }

    /**
     * Sets redemption_instructions
     *
     * @param string|null $redemption_instructions redemption_instructions
     *
     * @return self
     */
    public function setRedemptionInstructions($redemption_instructions)
    {
        if (is_null($redemption_instructions)) {
            throw new \InvalidArgumentException('non-nullable redemption_instructions cannot be null');
        }
        $this->container['redemption_instructions'] = $redemption_instructions;

        return $this;
    }

    /**
     * Gets ticket_expiration_date_time
     *
     * @return \DateTime
     */
    public function getTicketExpirationDateTime()
    {
        return $this->container['ticket_expiration_date_time'];
    }

    /**
     * Sets ticket_expiration_date_time
     *
     * @param \DateTime $ticket_expiration_date_time ticket_expiration_date_time
     *
     * @return self
     */
    public function setTicketExpirationDateTime($ticket_expiration_date_time)
    {
        if (is_null($ticket_expiration_date_time)) {
            throw new \InvalidArgumentException('non-nullable ticket_expiration_date_time cannot be null');
        }
        $this->container['ticket_expiration_date_time'] = $ticket_expiration_date_time;

        return $this;
    }

    /**
     * Gets max_comp_tickets
     *
     * @return float
     */
    public function getMaxCompTickets()
    {
        return $this->container['max_comp_tickets'];
    }

    /**
     * Sets max_comp_tickets
     *
     * @param float $max_comp_tickets max_comp_tickets
     *
     * @return self
     */
    public function setMaxCompTickets($max_comp_tickets)
    {
        if (is_null($max_comp_tickets)) {
            throw new \InvalidArgumentException('non-nullable max_comp_tickets cannot be null');
        }
        $this->container['max_comp_tickets'] = $max_comp_tickets;

        return $this;
    }

    /**
     * Gets payment_design_id
     *
     * @return \OpenAPI\Client\Model\SaveTicketSettingsRequestPaymentDesignID
     */
    public function getPaymentDesignId()
    {
        return $this->container['payment_design_id'];
    }

    /**
     * Sets payment_design_id
     *
     * @param \OpenAPI\Client\Model\SaveTicketSettingsRequestPaymentDesignID $payment_design_id payment_design_id
     *
     * @return self
     */
    public function setPaymentDesignId($payment_design_id)
    {
        if (is_null($payment_design_id)) {
            throw new \InvalidArgumentException('non-nullable payment_design_id cannot be null');
        }
        $this->container['payment_design_id'] = $payment_design_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


