<?php
/**
 * OpenAIApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * wallet-api
 *
 * API
 *
 * The version of the OpenAPI document: 2.1.602
 * Contact: development@wallet.inc
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * OpenAIApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OpenAIApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for archiveAssistant
     *
     * Archive Assistant.
     *
     */
    public function testArchiveAssistant()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for archiveThread
     *
     * Archive Thread.
     *
     */
    public function testArchiveThread()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for archiveVectorStore
     *
     * Archive VectorStore.
     *
     */
    public function testArchiveVectorStore()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createAssistant
     *
     * Create Assistant.
     *
     */
    public function testCreateAssistant()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createRunOnThread
     *
     * Create Run on Thread.
     *
     */
    public function testCreateRunOnThread()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createThread
     *
     * Create Thread.
     *
     */
    public function testCreateThread()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createThreadMessage
     *
     * Add Message to Thread.
     *
     */
    public function testCreateThreadMessage()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createVectorStore
     *
     * Create VectorStore.
     *
     */
    public function testCreateVectorStore()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for fetchAllAssistants
     *
     * Get all Assistants.
     *
     */
    public function testFetchAllAssistants()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for fetchAllThreads
     *
     * Get all Threads.
     *
     */
    public function testFetchAllThreads()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for fetchAllVectorStores
     *
     * Get all VectorStores.
     *
     */
    public function testFetchAllVectorStores()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for fetchAssistant
     *
     * Get Assistant.
     *
     */
    public function testFetchAssistant()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for fetchThreadMessages
     *
     * Get Thread's Messages.
     *
     */
    public function testFetchThreadMessages()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for restoreAssistant
     *
     * Restore Assistant.
     *
     */
    public function testRestoreAssistant()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for restoreThread
     *
     * Restore Thread.
     *
     */
    public function testRestoreThread()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for restoreVectorStore
     *
     * Restore VectorStore.
     *
     */
    public function testRestoreVectorStore()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateAssistant
     *
     * Update Assistant.
     *
     */
    public function testUpdateAssistant()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateThread
     *
     * Update Thread.
     *
     */
    public function testUpdateThread()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateVectorStore
     *
     * Update VectorStore.
     *
     */
    public function testUpdateVectorStore()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
